class ArtistLookup:
    golden_copy = {
        "cezanne": 0,
        "gauguin": 1,
        "kandinsky": 2,
        "rembrandt": 3,
        "rothko": 4
        # "kandinsky_abstract": 0,
        # "kandinsky_expressionism": 1,
        # "cezanne_cubism": 2,
        # "cezanne_impressionism": 3,
        # "cezanne_post_impressionism": 4,
        # "cezanne_romanticism": 5,
        # "renoir_impressionism": 6,
        # "gauguin_cloisonnism": 7,
        # "gauguin_impressionism": 8,
        # "gauguin_post_impressionism": 9,
        # "sargent_impressionism": 10,
        # "sargent_realism": 11,
        # "constable": 0,
        # "hopper": 1,
        # "kandinsky": 2,
        # "lowry": 3,
        # "monet": 4,
        # "rembrandt": 5,
        # "rothko": 6,
        # "rubens": 7,
        # "turner": 8,
        # "van-gogh": 9
    }
